skillMetadata:
  sections:
    - name: Nexcloud Login
      fields:
        - name: url
          type: text
          label: Enter CalDav URL
          value: ""
        - name: username
          type: email
          label: Enter your email address
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
