skillMetadata:
  sections:
    - name: Nexcloud Login
      fields:
        - name: my_string
          type: text
          label: Enter CalDav URL
          value: ""
        - name: my_email_address
          type: email
          label: Enter your email address
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
